name: podman # you probably want to 'snapcraft register <name>'
version: '0.11.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Manage pods, containers and container images
description: |
  `podman` is a tool for managing Pods, Containers, and Container Images
  in multiple formats including Docker/OSI images. It exposes the same
  command line interface as Docker, but runs containers unprivileged by
  default.

confinement: devmode # use 'strict' once you have the right plugs and slots

base: core18

parts:
  podman:
    plugin: go
    source: https://github.com/containers/libpod/archive/v0.11.1.1.tar.gz

